ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.hairup.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:mysql://127.0.0.1:3306/hairup"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "kriol"
    password = "Taller2014"
    maxPoolSize = 10
}